import Head from 'next/head';
import Image from 'next/image';
import Script from 'next/script';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" type="image/png" href="/images/favicon.png " />
        <link rel="stylesheet" href="/styles/bootstrap.min.css" />
        <link rel="stylesheet" href="/styles/slick.css" />
        <link rel="stylesheet" href="/styles/shortcode.css" />
        <link rel="stylesheet" href="/styles/base.css" />
        <link rel="stylesheet" href="/styles/style.css" />
        <link rel="stylesheet" href="/styles/responsive.css" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swapdefer " rel="stylesheet" />
      </Head>
      <main >
        {/* <!-- page wrapper --> */}
        <div className="page-wrapper">
          {/* <!-- Header Main Area --> */}
          <header className="site-header header-style-1">
            <div className="pre-header">
              <div className="container">
                <div className="d-flex justify-content-between  align-items-center">
                  <div className="pre-header-left">
                    <ul className="top-contact">
                      <li><i className="fa-solid fa-location-dot"></i>CRA 1D BIS # 61A - 94 </li>
                    </ul>
                  </div>
                  <div className="pre-header-right">
                    <ul className="top-contact d-inline">
                      <li><i className="fa-solid fa-clock"></i>Lun - Sab 8.00 AM - 5:00 PM </li>
                    </ul>
                    <ul className="social-icons d-inline">
                      <li>
                        <a target="_blank"
                          href="https://www.instagram.com/opticenteroficial/"
                          data-tooltip="Instagram"
                        >
                          <i className="fa fa-instagram"></i>
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <div className="site-header-menu">
              <div className="container">
                <div className="row">
                  <div className="col-md-12">
                    <div className="d-flex align-items-center">
                      <div className="site-branding flex-grow-1">
                        <a href="/">
                          <Image
                            className="logo-img"
                            alt="opticenter"
                            src='/images/logoOpticenter.webp'
                            height={143}
                            width={467}
                            priority={true}
                          />
                        </a>
                      </div>
                      <div className="site-navigation ml-auto">
                        <nav className="main-menu navbar-expand-xl navbar-light">
                          <div className="navbar-header">
                            {/* <!-- Togg le Button --> */}
                            <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                              <span className="fa fa-bars"></span>
                            </button>
                          </div>
                          <div className="collapse navbar-collapse clearfix" id="navbarSupportedContent">
                            <ul className="navigation clearfix">
                              <li><a href="#Bannerslider">Inicio</a></li>
                              <li><a href="#footer">Contacto</a></li>
                              <li className="d-lg-none"><a href="#cita">cita</a></li>
                            </ul>
                          </div>
                        </nav>
                      </div>
                      <div className="menu-right-box d-flex align-items-center">
                        <div className="header-button">
                          <a href="#cita" className="btn btn-outline">cita</a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </header>
          {/* <!-- Header Main Area End Here -->
          <!-- page content --> */}
          <div className="page-content">
            {/* <!-- Banner --> */}
            <section className="home-banner home-slider-first">
              <div id="Bannerslider" className="carousel slide" data-ride="carousel">
                <div className="carousel-inner">
                  <div className="carousel-item active">
                    <Image
                      className="img-fluid"
                      src="/images/banner/banner-01.webp"
                      alt="opticenter"
                      height={750}
                      width={1900}
                      priority={true}
                    />
                    <div className="carousel-caption">
                      <div className="container">
                        <div className="row">
                          <div className="col-xl-6 col-lg-7 col-md-7 col-sm-8  col-8">
                            <span className="shapewrapper-inner anim-1">ESPECIALISTA EN CUIDADO DE LOS OJOS</span>
                            <h1 className="anim-2">Servicio que te hará <br /><strong>vernos con nuevos ojos</strong></h1>
                            <div className="tagline anim-3 d-none d-sm-block">Brindamos siempre nuestros mejores servicios</div>
                            <div className="d-none d-sm-block mt-4">
                              <a href="https://wa.me/573174117065" target="_blank" className="btn anim-3">WhatsApp </a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="carousel-item">
                    <Image
                      className="img-fluid"
                      src="/images/banner/banner-02.webp"
                      alt="opticenter"
                      height={750}
                      width={1900}
                    />
                    <div className="carousel-caption">
                      <div className="container">
                        <div className="row">
                          <div className="col-xl-6 col-lg-7 col-md-7  col-sm-8 col-8">
                            <span className="shapewrapper-inner anim-1">Material de calidad</span>
                            <h1 className="anim-2">Dale la comodidad y la seguridad <br /><strong>que tus ojos necesitan.</strong></h1>
                            <div className="tagline anim-3 d-none d-sm-block">Garantía en todos nuestros productos</div>
                            <div className="d-none d-sm-block mt-4">
                              <a href="tel:3174117065" className="btn anim-3">llamanos </a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                {/* <!-- Left and right controls --> */}
                <a className="carousel-control-prev" href="#Bannerslider" data-slide="prev">
                  <span className="carousel-control-prev-icon"></span>
                </a>
                <a className="carousel-control-next" href="#Bannerslider" data-slide="next">
                  <span className="carousel-control-next-icon"></span>
                </a>
              </div>
            </section>
            {/* <!-- Banner End -->
            <!-- Features --> */}
            <section className="intro-section bg-lightgrey">
              <div className="container">
                <div className="row no-gutters bg-white box-shadow-01">
                  <div className="col-md-3 iconbox-border">
                    <div className="iconbox iconbox-style-3">
                      <div className="iconbox-inner">
                        <div className="iconbox-icon skincolor">
                          <i className="fa-solid fa-eye"></i>
                        </div>
                        <div className="iconbox-contents">
                          <div className="iconbox-title">
                            <h2>Cuidado de los ojos</h2>
                          </div>
                          <div className="iconbox-desc">
                            <p>Mejoramos tu visión y tu calidad de vida, con nuestras gafas medicadas.</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="col-md-3 iconbox-border">
                    <div className="iconbox iconbox-style-3">
                      <div className="iconbox-inner">
                        <div className="iconbox-icon skincolor">
                          <i className="fa-solid fa-child"></i>
                        </div>
                        <div className="iconbox-contents">
                          <div className="iconbox-title">
                            <h2>Niños</h2>
                          </div>
                          <div className="iconbox-desc">
                            <p>Cuida tus niños así como lo hacemos nosotros, la mejor atención para ellos.</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="col-md-3 iconbox-border">
                    <div className="iconbox iconbox-style-3">
                      <div className="iconbox-inner">
                        <div className="iconbox-icon skincolor">
                          <i className="fa-solid fa-glasses"></i>
                        </div>
                        <div className="iconbox-contents">
                          <div className="iconbox-title">
                            <h2>Marcos</h2>
                          </div>
                          <div className="iconbox-desc">
                            <p>Gran variedad disponible para elegir: colores, marcas, tamaños; Lo mejor y a la moda.</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="col-md-3">
                    <div className="iconbox iconbox-style-3">
                      <div className="iconbox-inner">
                        <div className="iconbox-icon skincolor">
                          <i className="fa-solid fa-user-doctor"></i>
                        </div>
                        <div className="iconbox-contents">
                          <div className="iconbox-title">
                            <h2>¿Consulta gratuita?</h2>
                          </div>
                          <div className="iconbox-desc">
                            <p>Consulta gratuita para el examen previo, si se compran los lentes.</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
            {/* <!-- Features end -->
            <!-- Welcome --> */}
            <section className="bg-lightgrey welcome-company">
              <div className="container">
                <div className="row align-items-lg-center align-items-md-end">
                  <div className="col-md-12 col-lg-6">
                    <Image
                      src="/images/img-01-new.webp"
                      className="img-fluid"
                      alt="optometria para niños"
                      height={585}
                      width={582}
                    />
                  </div>
                  <div className="col-md-12 col-lg-6 mt-sm-30 pb-50">
                    <div className="section-title mt-md-50">
                      <h4 className="subheading skincolor">BIENVENIDO A OPTICENTER</h4>
                      <h2>PRESERVAMOS, MEJORAMOS Y  <strong> PROTEGEMOS SU VISIÓN</strong></h2>
                    </div>
                    <p>
                      No eres nada sin tus ojos,
                      <a className="opt-underline-dotted"
                        href="https://www.masvision.es/blog/salud-visual/10-consejos-prevenir-miopia/"
                        target="_blank">
                        protégelos
                      </a>
                      con hábitos saludables, visítanos y recibe los mejores tips y cuidados de opticenter.
                    </p>
                    <p>
                      <a className="opt-underline-dotted"
                        href="https://www.infosalus.com/salud-investigacion/noticia-diez-consejos-cuidar-vista-20150216135142.html"
                        target="_blank">
                        Cuida tus ojos,
                      </a> lo hacemos por ti, para que veas y te sientas bien.</p>
                    <div className="d-none d-sm-block mt-4">
                      <a href="https://www.google.com/maps/place/Opticenter/@3.4739793,-76.495721,17z/data=!3m1!4b1!4m5!3m4!1s0x8e30a87fc3b56b2f:0x1f6deaf194d84ef5!8m2!3d3.4739793!4d-76.4935323"
                        className="btn anim-3"
                        target="_blank"
                      >
                        VISÍTANOS
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </section>
            {/* <!-- Welcome end -->
            <!-- About Vision --> */}
            <section className="section-md">
              <div className="container">
                <div className="row">
                  <div className="col-lg-6 pr-4">
                    <div className="section-title with-lead">
                      <h4 className="subheading skincolor">SU VISIÓN ES NUESTRA VISIÓN</h4>
                      <h2>NO SOLO ATENCIÓN, SINO<strong> UNA <br />MEJOR EXPERIENCIA DE ATENCIÓN</strong></h2>
                      <div className="lead">
                        Estamos pendientes antes y después del proceso ocular, siempre atentos a las
                        preguntas de nuestros clientes, acompañamiento constante durante el proceso,
                        asesoría y precios accesibles.
                      </div>
                    </div>
                    <div className="row">
                      <div className="col-md-6">
                        <div className="iconbox iconbox-style-2">
                          <div className="iconbox-inner">
                            <div className="iconbox-contents">
                              <div className="iconbox-title">
                                <h2>Médicos Calificados</h2>
                              </div>
                              <div className="iconbox-desc">
                                <p>Expertos dedicados al cuidado y protección ocular.</p>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="col-md-6">
                        <div className="iconbox iconbox-style-2">
                          <div className="iconbox-inner">
                            <div className="iconbox-contents">
                              <div className="iconbox-title">
                                <h2>Equipamiento moderno</h2>
                              </div>
                              <div className="iconbox-desc">
                                <p>Marcos de excelente calidad, diversos para damas y caballeros.</p>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="row">
                      <div className="col-md-6">
                        <div className="iconbox iconbox-style-2">
                          <div className="iconbox-inner">
                            <div className="iconbox-contents">
                              <div className="iconbox-title">
                                <h2>Ayuda de emergencia</h2>
                              </div>
                              <div className="iconbox-desc">
                                <p>clínicas para tratamientos quirúrgicos oftalmológicos</p>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="col-md-6">
                        <div className="iconbox iconbox-style-2">
                          <div className="iconbox-inner">
                            <div className="iconbox-contents">
                              <div className="iconbox-title">
                                <h2>Enfoque individual</h2>
                              </div>
                              <div className="iconbox-desc">
                                <p>Personalice sus lentes y adquiera la protección que necesitas.</p>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="col-lg-6 mt-md-30 text-md-center mb-lg-30">
                    <Image
                      src="/images/01.webp"
                      className="img-fluid img-shadow"
                      alt="cuida tus ojos"
                      width={550}
                      height={730}
                    />
                  </div>
                </div>
              </div>
            </section>
            {/* <!-- About Vision end -->
            <!-- Why Choose Us --> */}
            <section className="counter-section white-color">
              <div className="container">
                <div className="row">
                  <div className="col-lg-6">
                    <div className="play-video align-items-center d-flex white-color">
                      <a
                        target="_blank"
                        href="https://www.youtube.com/watch?v=smhKRoLLvDQ&list=PL5n65gEBgEz3r2V_Stvaqe9UxS87XfSOR&index=2"
                      >
                        <i className="fa-solid fa-play"></i>
                      </a>
                      <h4>Más allá de los lentes</h4>
                    </div>
                    <div className="section-title section-title-white pt-4 mt-2">
                      <h4 className="subheading">POR QUÉ ELEGIRNOS</h4>
                      <h2>CALIDAD EN NUESTROS<strong> MARCOS Y LENTES</strong></h2>
                    </div>
                  </div>
                  <div className="col-lg-6 mt-4 pt-3">
                    <div className="row">
                      <div className="col-md-4">
                        <div className="db-fid inside db-fid-boxstyle-style2 db-fidbox-style-2">
                          <div className="db-fld-contents">
                            <div className="db-circle-outer" data-digit="97" data-fill="#fff" data-before="" data-before-type="sup" data-after="<sub>%</sub>" data-after-type="sub" data-size="145" data-emptyfill="#000301" data-thickness="7" data-gradient="">
                              <div className="db-circle-w">
                                <div className="db-circle"></div>
                                <div className="db-circle-overlay">
                                  <div className="db-circle-number"></div>
                                </div>
                              </div>
                              <div className="db-fid-title-w">
                                <h3 className="db-fid-title"><span>Doctores Expertos</span></h3>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="col-md-4">
                        <div className="db-fid inside db-fid-boxstyle-style2 db-fidbox-style-2">
                          <div className="db-fld-contents">
                            <div className="db-circle-outer" data-digit="99" data-fill="#fff" data-before="" data-before-type="sup" data-after="<sub>%</sub>" data-after-type="sub" data-size="145" data-emptyfill="#000301" data-thickness="7" data-gradient="">
                              <div className="db-circle-w">
                                <div className="db-circle"></div>
                                <div className="db-circle-overlay">
                                  <div className="db-circle-number"></div>
                                </div>
                              </div>
                              <div className="db-fid-title-w">
                                <h3 className="db-fid-title"><span>Trabajo de calidad</span></h3>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="col-md-4">
                        <div className="db-fid inside db-fid-boxstyle-style2 db-fidbox-style-2">
                          <div className="db-fld-contents">
                            <div className="db-circle-outer" data-digit="95" data-fill="#fff" data-before="" data-before-type="sup" data-after="<sub>%</sub>" data-after-type="sub" data-size="145" data-emptyfill="#000301" data-thickness="7" data-gradient="">
                              <div className="db-circle-w">
                                <div className="db-circle"></div>
                                <div className="db-circle-overlay">
                                  <div className="db-circle-number"></div>
                                </div>
                              </div>
                              <div className="db-fid-title-w">
                                <h3 className="db-fid-title"><span>Equipo dedicado</span></h3>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
            {/* <!-- Why Choose Us end -->
            <!-- Our Service --> */}
            <section className="section-md" id="services">
              <div className="container">
                <div className="row justify-content-center">
                  <div className="col-md-8">
                    <div className="section-title text-center">
                      <h4 className="subheading skincolor">NUESTROS SERVICIOS</h4>
                      <h2>UNA AMPLIA GAMA DE<strong><br /> SERVICIOS DE OPTOMETRÍA</strong></h2>
                    </div>
                  </div>
                </div>
                <div className="row pt-3">
                  <div className="col-lg-4 col-md-6 col-sm-12">
                    <div className="service-box service-style-1">
                      <div className="service-thumbnail">
                        <div className="service-thumbnail-inner">
                          <Image
                            src="/images/services/service-01.webp"
                            className="img-fluid"
                            alt="oftamologia"
                            height={683}
                            width={1024}
                          />
                        </div>
                      </div>
                      <div className="service-content">
                        <div className="service-inner">
                          <h3 className="service-box-title"><b>Variedad en marcos</b></h3>
                          <div className="service-desc">
                            <p>
                              Gran diversidad de marcos que se ajustan a cualquier estilo ideal
                              de nuestros clientes.
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="col-lg-4 col-md-6 col-sm-12">
                    <div className="service-box service-style-1">
                      <div className="service-thumbnail">
                        <div className="service-thumbnail-inner">
                          <Image
                            src="/images/services/service-02.webp"
                            className="img-fluid"
                            alt="opticenter"
                            width={1024}
                            height={680}
                          />
                        </div>
                      </div>
                      <div className="service-content">
                        <div className="service-inner">
                          <h3 className="service-box-title"><b>Calidad Certificada</b></h3>
                          <div className="service-desc">
                            <p>
                              Lentes con la última tecnología en protección en los ojos.
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="col-lg-4 col-md-6 col-sm-12">
                    <div className="service-box service-style-1">
                      <div className="service-thumbnail">
                        <div className="service-thumbnail-inner">
                          <Image
                            src="/images/services/service-03.webp"
                            className="img-fluid"
                            alt="lentes transitions"
                            width={1200}
                            height={800}
                          />
                        </div>
                      </div>
                      <div className="service-content">
                        <div className="service-inner">
                          <h3 className="service-box-title"><b>Lentes Transitions</b></h3>
                          <div className="service-desc">
                            <p>Lentes que se adaptan automáticamente a los cambios de luz</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
            {/* <!-- Our Service end -->
            <!-- Appointment --> */}
            <section id="cita" className="get-appointment">
              <div className="container">
                <div className="row justify-content-center">
                  <div className="col-lg-12">
                    <div className="section-title text-center">
                      <h4 className="subheading skincolor">PEDIR CITA</h4>
                      <h2 className="white-color">RESERVA<strong><br />LA CITA CON UN DOCTOR</strong></h2>
                    </div>
                  </div>
                </div>
              </div>
            </section>
            <section className="bg-lightgrey appointment-from">
              <div className="container">
                <div className="row  box-shadow-02">
                  <div className="col-lg-4 appointment-image">
                  </div>
                  <div className="col-lg-8 appointment-inner">
                    <h3>Nos comunicaremos con usted lo más pronto posible.</h3>
                    <p>Le avisaremos por cualquier canal de comunicación que nos suministres.</p>
                    <div className="contact-form">
                      <form id="formy">
                        <div className="form-row">
                          <div className="form-group col-lg-6">
                            <input
                              id="name"
                              type="text"
                              className="form-control"
                              placeholder="Nombre"
                              name="name"
                              required
                              minLength="4"
                            />
                          </div>
                          <div className="form-group col-lg-6">
                            <input
                              id="email"
                              type="email"
                              className="form-control"
                              placeholder="Correo Electrónico"
                              name="email" aria-required="true"
                              required
                              minLength="10"
                            />
                          </div>
                          <div className="form-group col-lg-6">
                            <input
                              id="phone"
                              type="number"
                              className="form-control"
                              placeholder="Teléfono"
                              name="phone"
                              required
                            />
                          </div>
                          <div className="form-group col-lg-6">
                            <input
                              id="subject"
                              type="text"
                              className="form-control"
                              placeholder="Asunto"
                              name="subject"
                              required
                              minLength="4"
                            />
                          </div>
                          <div className="form-group col-lg-12">
                            <textarea
                              id="comment"
                              className="form-control"
                              placeholder="Mensaje"
                              name="message"
                              cols="45"
                              rows="5"
                              aria-required="true"
                              style={{ resize: 'none' }}
                              required
                              maxLength="5000"
                            ></textarea>
                          </div>
                          <div className="form-group col-lg-12">
                            <button
                              type="submit"
                              id="btn-agenda"
                              className="btn">
                              Envía mensaje
                            </button>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </section>
            {/* <!-- Appointment end -->
            <!-- Counter --> */}
            <section className="bg-lightgrey section-smt">
              <div className="container">
                <div className="row">
                  <div className="col-md-3">
                    <div className="counter counter-style-1">
                      <div className="fld-contents">
                        <h4 className="counter-contents">
                          <span
                            data-appear-animation="animateDigits"
                            data-to="10"
                            data-interval="1"
                            data-from="0"
                            data-before=""
                            data-before-style=""
                            data-after=""
                            data-after-style=""
                          >
                          </span>
                        </h4>
                        <h6 className="counter-title">
                          <span>Años de experiencia</span>
                        </h6>
                      </div>
                    </div>
                  </div>
                  <div className="col-md-3">
                    <div className="counter counter-style-1">
                      <div className="fld-contents">
                        <h4 className="counter-contents">
                          <span
                            data-appear-animation="animateDigits"
                            data-to="800"
                            data-interval="5"
                            data-from="0"
                            data-before=""
                            data-before-style=""
                            data-after=""
                            data-after-style=""
                          >
                          </span>
                        </h4>
                        <h6 className="counter-title">
                          <span>Marcos</span>
                        </h6>
                      </div>
                    </div>
                  </div>
                  <div className="col-md-3">
                    <div className="counter counter-style-1">
                      <div className="fld-contents">
                        <h4 className="counter-contents">
                          <span
                            data-appear-animation="animateDigits"
                            data-to="6"
                            data-interval="1"
                            data-from="0"
                            data-before=""
                            data-before-style=""
                            data-after=""
                            data-after-style=""
                          >
                          </span>
                        </h4>
                        <h6 className="counter-title">
                          <span>Servicios Diferentes</span>
                        </h6>
                      </div>
                    </div>
                  </div>
                  <div className="col-md-3">
                    <div className="counter counter-style-1">
                      <div className="fld-contents">
                        <h4 className="counter-contents">
                          <span
                            data-appear-animation="animateDigits"
                            data-to="1600"
                            data-interval="5"
                            data-from="0"
                            data-before=""
                            data-before-style=""
                            data-after=""
                            data-after-style=""
                          >
                          </span>
                        </h4>
                        <h6 className="counter-title">
                          <span>Pacientes Felices</span>
                        </h6>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
            {/* <!-- Counter end --> */}
          </div>
          {/* <!-- page content End -->
     <!-- footer --> */}
          <footer className="footer site-footer" id="footer">
            <div className="footer-top skin-bg-color">
              <div className="container">
                <div className="row d-flex white-color align-items-center">
                  <div className="col-lg-8">
                    <div className="iconbox iconbox-style-6">
                      <div className="iconbox-inner d-flex">
                        <div className="iconbox-icon">
                          <i className="fa-solid fa-headset"></i>
                        </div>
                        <div className="iconbox-contents">
                          <div className="iconbox-title">
                            <h2>
                              Si tienes alguna pregunta, duda o inquietud
                              <strong>
                                puedes mandarnos un mensaje o incluso pedir la cita
                                vía WhatsApp.
                              </strong>
                            </h2>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="col-lg-4 mt-md-30 text-lg-right">
                    <a href="https://wa.me/+573174117065?text=Quiero%20pedir%20mi%20cita"
                      className="btn btn-dark"
                      target="_blank"
                    >
                      Cita WhatsApp
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div className="container">
              <div className="row">
                <div className="col-xs-12 col-lg-4 mb-md-5 d-md-flex justify-content-center">
                  <div>
                    <div className="footerlogo mb-4 text-md-center text-lg-left">
                      <h2 style={{ fontWeight: 900 }}>Opticenter</h2>
                    </div>
                    <p className="mb-0">
                      Consultorio optométrico, venta de lentes oftálmicos y lentes de contacto,
                      monturas nacionales e importadas oftálmicas y de sol.
                    </p>
                    <div className="social-links-wrapper d-md-none d-lg-block">
                      <ul className="social-icons">
                        <li>
                          <a href="https://www.instagram.com/opticenteroficial/"
                            className="tooltip-top"
                            data-toggle="tooltip"
                            data-placement="top"
                            data-tooltip="Instagram"
                            target="_blank"
                          >
                            <i className="fa fa-instagram"></i>
                          </a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div className="col-xs-12 col-sm-6 col-md-6 col-lg-4 mt-md-30 d-md-flex justify-content-center">
                  <div>
                    <h6 className="footer-widget-title">Nuestros Servicios</h6>
                    <ul className="list-unstyled">
                      <li><i className="fa-solid fa-circle-check text-blue-one"></i>
                        <a> Lentes Transitions</a>
                      </li>
                      <li><i className="fa-solid fa-circle-check text-blue-one"></i>
                        <a> Corrección de la visión</a>
                      </li>
                      <li><i className="fa-solid fa-circle-check text-blue-one"></i>
                        <a> Exámenes y valoraciones</a>
                      </li>
                      <li><i className="fa-solid fa-circle-check text-blue-one"></i>
                        <a> Lentes Antireflejo</a>
                      </li>
                      <li><i className="fa-solid fa-circle-check text-blue-one"></i>
                        <a> Convenios Empresariales</a>
                      </li>
                    </ul>
                  </div>
                </div>
                <div className="col-xs-12 col-sm-6 col-md-6 col-lg-4 address-box mt-md-30 d-md-flex justify-content-center">
                  <div>
                    <h6 className="footer-widget-title">Encuéntranos</h6>
                    <div className="d-flex">
                      <i className="fa-solid fa-location-dot"></i>
                      <p><strong>OPTICENTER</strong>
                        <br />CRA 1D BIS #61A - 94</p>
                    </div>
                    <div className="d-flex">
                      <i className="fa-solid fa-mobile-screen-button"></i>
                      <p>(+57) 317 411 7065 </p>
                    </div>
                    <div className="d-flex">
                      <i className="fa-solid fa-envelope"></i>
                      <p>info@opticenter.com</p>
                    </div>
                    <div className="d-flex">
                      <i className="fa-solid fa-clock"></i>
                      <div>
                        <p >Lun - Vie 8.00 AM - 6:00 PM</p>
                      </div>
                    </div>
                    <div className="d-flex">
                      <i className="fa-solid fa-clock"></i>
                      <div>
                        <p>Lun - Sab 8.00 AM - 5:00 PM</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="bottom-footer">
                <div className="row">
                  <div className="col-sm-12 text-center">
                    Copyright © 2021
                    <a href="https://overweb.com.co" target="_blank"> OVERWEB</a>
                    . All rights reserved.
                  </div>
                </div>
              </div>
            </div>
          </footer>
        </div>
        {/* <!-- page wrapper End --> */}
        <div id="notify"></div>
        <a className="whatsapp" href="https://wa.me/573174117065">
          <i className="fa-brands fa-whatsapp fa-3x"></i>
        </a>
      </main>
      <Script strategy="beforeInteractive" src="js/jquery.min.js" />
      <Script strategy="lazyOnload" src="js/popper.min.js" />
      <Script strategy="lazyOnload" src="js/bootstrap.min.js" />
      <Script strategy="lazyOnload" src="js/jquery-waypoints.js" />
      <Script strategy="lazyOnload" src="js/jquery.appear.js" />
      <Script strategy="lazyOnload" src="js/numinate.min.js" />
      <Script strategy="lazyOnload" src="js/slick.min.js" />
      <Script strategy="lazyOnload" src="js/jquery.prettyPhoto.js" />
      <Script strategy="lazyOnload" src="js/circle-progress.js" />
      <Script strategy="lazyOnload" src="js/jquery.event.move.js" />
      <Script strategy="lazyOnload" src="js/jquery.twentytwenty.js" />
      <Script strategy="lazyOnload" src="js/scripts.js" />
      <Script strategy="lazyOnload" src="https://kit.fontawesome.com/5ffca20140.js" crossorigin="anonymous" />
      <Script strategy="lazyOnload" src="js/forms/citas/agenda.js" />
    </>
  )
}
