import Whatsapp from '@/components/custom/whatsapp';
import BannerSoporte from '@/components/home/BannerSoporte';
import Calidad from '@/components/home/Calidad';
import Counter from '@/components/home/Counter';
import Form from '@/components/home/Form';
import Services from '@/components/home/Services';
import ServicesSlider from '@/components/home/ServicesSlider';
import Slider from '@/components/home/slider';
import Welcome from '@/components/home/Welcome';
import WorkStatus from '@/components/home/WorkStatus';
import Footer from '@/layouts/Footer';
import Nav from '@/layouts/nav';
import Head from 'next/head';
import Script from 'next/script';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" type="image/png" href="/images/favicon.png " />
      </Head>
      <main >
        <div className="page-wrapper">
          <div className="page-content">
            <Nav />
            <Slider />
            <ServicesSlider />
            <Welcome />
            <Calidad />
            <WorkStatus />
            <Services />
            <Form />
            <Counter />
            <BannerSoporte />
            <Whatsapp number={573174117065} />
            <Footer />
          </div>
        </div>
      </main>
      <Script strategy="beforeInteractive" src="js/jquery.min.js" />
      <Script strategy="lazyOnload" src="js/popper.min.js" />
      <Script strategy="lazyOnload" src="js/bootstrap.min.js" />
      <Script strategy="lazyOnload" src="js/jquery-waypoints.js" />
      <Script strategy="lazyOnload" src="js/jquery.appear.js" />
      <Script strategy="lazyOnload" src="js/numinate.min.js" />
      <Script strategy="lazyOnload" src="js/slick.min.js" />
      <Script strategy="lazyOnload" src="js/jquery.prettyPhoto.js" />
      <Script strategy="lazyOnload" src="js/circle-progress.js" />
      <Script strategy="lazyOnload" src="js/jquery.event.move.js" />
      <Script strategy="lazyOnload" src="js/jquery.twentytwenty.js" />
      <Script strategy="lazyOnload" src="js/scripts.js" />
      <Script strategy="lazyOnload" src="https://kit.fontawesome.com/5ffca20140.js" crossOrigin="anonymous" />
      <Script strategy="lazyOnload" src="js/forms/citas/agenda.js" />
    </>
  )
}
